### ISSUE TITLE
When Redux 4 will be supported?

### ISSUE THREAD

**Issue by brneto** [zalmoxisus/redux-devtools-instrument#20]
Redux 4 is now stable. [#391](https://github.com/reduxjs/redux-devtools/pull/391), [#399](https://github.com/reduxjs/redux-devtools/pull/399), [#400 ](https://github.com/reduxjs/redux-devtools/pull/400) seems to have been fixed and [redux-devtools](https://github.com/reduxjs/redux-devtools) extension seems to work with Redux 4, but the package.json of this still shows a [peer dependency of Redux ^3.5.2](https://github.com/zalmoxisus/redux-devtools-instrument/blob/73ae9765a76adb5efec205412175f66805fb99ca/package.json#L50). Would be safe to adjust the peer dependency to allow Redux 4 or are there still changes that should be made to support it? Is there anything we could do to help?

**Comment by SavePointSam** [comment]
related:
- https://github.com/reduxjs/redux-devtools/issues/399
- https://github.com/reduxjs/redux-devtools/pull/400

**Comment by navata** [comment]
I have updated redux 4, which has issue as below: 
[https://i.stack.imgur.com/14rfT.png](url)

I think we need upgrade version for supporting redux 4.

**Comment by navata** [comment]
I have updated redux 4, which has issue as below: 
[https://i.stack.imgur.com/14rfT.png](url)

I think we need upgrade version for supporting redux 4.

**Comment by jhen0409** [comment]
Fixed in #19.
