### ISSUE TITLE
Hook to handle Immutable data structures

### ISSUE THREAD

**Issue by gschwa** [zalmoxisus/redux-devtools-instrument#3]
Bringing this issue over from redux-devtools. 

I am currently using seamless-immutable and when starting from a committed state the `nextComputedStates` does not have the immutable functions. The issue lives in the `recomputeStates` function: https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L109 . Any chance of a post-process hook to make it immutable?

I did try preprocessing the liftedState before calling the importState action but no luck.

**Comment by zalmoxisus** [comment]
Hey @gschwa,

Sorry, I still didn't get time to look into it.

If the problem comes from `recomputeStates` then even without importing, cancel (toggle) actions from the monitor doesn't work as well when having the states immutable, right?

**Comment by gschwa** [comment]
@zalmoxisus interestingly toggling the actions works fine maybe because the state is not destroyed completely?

**Comment by gschwa** [comment]
Good news. I was able to fix it by making the `committedState` immutable before calling `importState`.
