### ISSUE TITLE
DevTools.instrument() swallows exceptions?

### ISSUE THREAD

**Issue by jonase** [zalmoxisus/redux-devtools-instrument#5]
In one of my (redux-thunk) action creators I'm attempting something similar to

```
function someActionCreator() {
  return (dispatch) => {
    try {
      dispatch(someAction);
    } catch (e) {
      dispatch(someOtherAction);
    }
  }
}
```

but this doesn't seem to work well with redux-devtools. I'm not completely sure if I've been able to diagnose the problem correctly but I'm wondering if the fact that the exception gets caught [here](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L90-L98) and not (AFAIKT) gets rethrown has something to do with my problem?

If I disable redux-devtools I'm able to catch the exception in the action creator.

**Comment by gaearon** [comment]
Curious: what is your use case for catching exceptions inside reducer this way? The system would be in an inconsistent state by now anyway.

**Comment by jonase** [comment]
@gaearon I agree, it's perhaps not something I should be doing. I don't quite understand in what sense the system would end up in an inconsistent state. If the (pure) reducer throws wouldn't the stack simply unroll until I catch it in the action creator? If I choose to not call `dispatch` again in the thunk wouldn't the store simply be left alone?

My use case is that I have user defined "transformations" (compiled down to reducer functions) with different (also user defined) error strategies. One of the strategies is "abort" which should leave the store untouched. If this happens, I want to report it. I don't want to add some ad-hoc `transformationAborted` key to the data structure. That's why I'm thinking that I would catch the exception and dispatch an action like `SHOW_NOTIFICATION`.

Another approach I'm considering is to run the reducer in the action creator and emit actions like `TRANSFORMATION_SUCCESS`, `TRANSFORMATION_FAILURE` etc. This means moving all of the real complexity to the action creator, which is fine and not unusual with redux.

I'm still interested in knowing if this is something that just happens to work in redux without DevTools and not something we should rely on.

**Comment by zalmoxisus** [comment]
Well, we could add a `catchErrors` parameter, which would be `true` by default. So, you would be able to disable that by using `DevTools.instrument({ catchErrors: false })`.

**Comment by jonase** [comment]
@zalmoxisus @gaearon I think it would be nice if devtools doesn't change how exceptions are handled in redux. So I wonder if the default should be the other way around? Re-throw by default and add a `{ catchErrors: true }` option?

**Comment by zalmoxisus** [comment]
> I wonder if the default should be the other way around? Re-throw by default and add a `{ catchErrors: true }` option?

@jonase, I wouldn't do that, at least, because it would be a breaking change and it's one of the main features of Redux DevTools (see [Dan's talk](https://youtu.be/xsSnOQynTHs?t=1468) and [mine](https://youtu.be/cbXLohVbzNI?t=451)).

If @gaearon agree, I can add this parameter. It would be useful also for the extension and for Remote Redux DevTools as there's an option to enable/disable global error catching.

**Comment by brabeji** [comment]
Hi all, today this got me so I am adding my two cents.

Similarly to @jonase 's point I am wondering why do devtools even catch and process errors from reducers? Certainly I may not see the benefit or implications of not doing so.

Synchronous logging is fine but the original issue for me was that instrument rethrows error in `setTimeout` [here](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L94) which moved the error to the end of log where I wasn't looking - I was confident that redux is synchronous.

**Comment by zalmoxisus** [comment]
OK, I've implemented in https://github.com/zalmoxisus/redux-devtools-instrument/commit/93ad9c7ec6252b46ff9a815eb770f41d1e05ec42.

The question is whether we should release it in `1.1.0` or `2.0.0` as being a breaking change for Redux DevTools. 

@gaearon, what do you think?

P.S. tests on travis failed as [it has some issues right now with `npm install`](https://www.traviscistatus.com/incidents/fg9f43y4m8j2).

**Comment by zalmoxisus** [comment]
It's up in `1.1.0`.
